### ISSUE TITLE
Error while running toy_benchmark

### ISSUE THREAD

**Issue by CodeATA** [technion-csl/mosmodel#15] opened 2021-08-19 07:17 UTC
I get the following error message while running make for the default toy_benchmark

> echo ========== [INFO] start producing: experiments/single_page_size/layout2mb/repeat1/perf.out ==========
> ARGS_FOR_MOSALLOC=" -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 104857600 -bps 180355072 -bs1 0 -be1 0 -bs2 0 -be2 180355072"
> /home/chendongwei/tlb-workspace/mosmodel/scripts/runBenchmark.py --submit_command "/home/chendongwei/tlb-workspace/mosmodel/scripts/measureGeneralMetrics.sh /home/chendongwei/tlb-workspace/mosmodel/scripts/setCpuMemoryAffinity.sh $(( 2 - 1 )) \
> 	/home/chendongwei/tlb-workspace/mosmodel/mosalloc/runMosalloc.py --library /home/chendongwei/tlb-workspace/mosmodel/mosalloc/src/libmosalloc.so $ARGS_FOR_MOSALLOC --analyze" -- \
> 	/home/chendongwei/tlb-workspace/mosmodel/toy_benchmark experiments/single_page_size/layout2mb/repeat1/
> ========== [INFO] start producing: experiments/single_page_size/layout2mb/repeat1/perf.out ==========
> creating a new output directory /home/chendongwei/tlb-workspace/mosmodel/experiments/single_page_size/layout2mb/repeat1/ ...
> copying the benchmark files to /home/chendongwei/tlb-workspace/mosmodel/experiments/single_page_size/layout2mb/repeat1/...
> warming up before running...
> running the benchmark /home/chendongwei/tlb-workspace/mosmodel/toy_benchmark...
> the full submit command is:
> 	/home/chendongwei/tlb-workspace/mosmodel/scripts/measureGeneralMetrics.sh /home/chendongwei/tlb-workspace/mosmodel/scripts/setCpuMemoryAffinity.sh 1 	/home/chendongwei/tlb-workspace/mosmodel/mosalloc/runMosalloc.py --library /home/chendongwei/tlb-workspace/mosmodel/mosalloc/src/libmosalloc.so  -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 104857600 -bps 180355072 -bs1 0 -be1 0 -bs2 0 -be2 180355072 --analyze ./run.sh
> waiting for the run to complete...
> Traceback (most recent call last):
>   File "/home/chendongwei/tlb-workspace/mosmodel/scripts/runBenchmark.py", line 105, in <module>
>     benchmark_run.wait()
>   File "/home/chendongwei/tlb-workspace/mosmodel/scripts/runBenchmark.py", line 53, in wait
>     raise subprocess.CalledProcessError(self._run_process.returncode, ' '.join(self._run_process.args))
> subprocess.CalledProcessError: Command '/home/chendongwei/tlb-workspace/mosmodel/scripts/measureGeneralMetrics.sh /home/chendongwei/tlb-workspace/mosmodel/scripts/setCpuMemoryAffinity.sh 1 /home/chendongwei/tlb-workspace/mosmodel/mosalloc/runMosalloc.py --library /home/chendongwei/tlb-workspace/mosmodel/mosalloc/src/libmosalloc.so -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 104857600 -bps 180355072 -bs1 0 -be1 0 -bs2 0 -be2 180355072 --analyze ./run.sh' returned non-zero exit status 139.
> /home/chendongwei/tlb-workspace/mosmodel/experiments/template.mk:35: recipe for target 'experiments/single_page_size/layout2mb/repeat1/perf.out' failed
> make: *** [experiments/single_page_size/layout2mb/repeat1/perf.out] Error 1

I tried to run the submit command and got a segmentation fault. But when I replaced `./run.sh` with `./gups.py`, the command exited without an error. I also tried to do the same replacement in runBenchmark.py and got an identical error message with the exit code changing from 139 to 245.

**Comment by idanyani** [comment] 2021-08-19 09:14
Can you please upload or post the contents of the following files:
experiments/single_page_size/layout2mb/repeat1/perf.out
experiments/single_page_size/layout2mb/repeat1/benchmark.log
?

**Comment by CodeATA** [comment] 2021-08-19 09:53
[benchmark.log](https://github.com/technion-csl/mosmodel/files/7013460/benchmark.log)
[perf.out](https://github.com/technion-csl/mosmodel/files/7013462/perf.txt)

**Comment by magbarya** [comment] 2021-08-19 12:39
There was a known issue in some old version of bash that causes Segmentation Fault when using Mosalloc.
Can you please check your bash version and upgrade it to some new version (5.0 or an earlier version)?
Thanks.

**Comment by CodeATA** [comment] 2021-08-19 13:21
I updated bash from 4.3.48(1)-release to 5.1.8(1)-release but still got the same error message. bash version 5.0.0(1)-release made no difference. The contents of benchmark.log are posted below.

```
this CPU supports energy events
Running the following command:
perf stat --field-separator=, --output=perf.out --event ref-cycles,cpu-cycles,instructions,dtlb_load_misses.miss_causes_a_walk,dtlb_load_misses.stlb_hit,dtlb_load_misses.stlb_hit_2m,dtlb_load_misses.stlb_hit_4k,dtlb_load_misses.walk_completed,dtlb_load_misses.walk_completed_1g,dtlb_load_misses.walk_completed_2m_4m,dtlb_load_misses.walk_completed_4k,dtlb_load_misses.walk_duration,dtlb_store_misses.miss_causes_a_walk,dtlb_store_misses.stlb_hit,dtlb_store_misses.stlb_hit_2m,dtlb_store_misses.stlb_hit_4k,dtlb_store_misses.walk_completed,dtlb_store_misses.walk_completed_1g,dtlb_store_misses.walk_completed_2m_4m,dtlb_store_misses.walk_completed_4k,dtlb_store_misses.walk_duration -- perf stat --field-separator=, --output=perf.out --event power/energy-cores/,power/energy-pkg/,power/energy-ram/ --cpu=0 --  time --format=seconds-elapsed,%e\nuser-time-seconds,%U\nkernel-time-seconds,%S\nmax-resident-memory-kb,%M --output=time.out /home/chendongwei/tlb-workspace/mosmodel/scripts/setCpuMemoryAffinity.sh 1 /home/chendongwei/tlb-workspace/mosmodel/mosalloc/runMosalloc.py --library /home/chendongwei/tlb-workspace/mosmodel/mosalloc/src/libmosalloc.so -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 104857600 -bps 180355072 -bs1 0 -be1 0 -bs2 0 -be2 180355072 --analyze ./run.sh
Binding the process to memory node: 1,
and its local CPU cores: 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47
Allocating hugepages on node1...
---------------- DEBUG INFO ----------------
Reserving hugepages...
Currently:
  # of 2MB pages(node1) == 137
  # of 1GB pages(node1) == 0
Trying to allocate 0 huge pages
Trying to allocate 137 large pages
Updated:
  # of 2MB pages(node1) == 137
  # of 1GB pages(node1) == 0
--------------------------------------------
Huge pages were set correctly
./run.sh: line 3: 10871 Segmentation fault      (core dumped) ./gups.py
```

**Comment by magbarya** [comment] 2021-08-19 20:25
Can you please run it under debugger, please run the following commands from your shell:
cd experiments/single_page_size/layout2mb/repeat1
gdb --args python /home/chendongwei/tlb-workspace/mosmodel/mosmodel/mosalloc/runMosalloc.py --library /home/chendongwei/tlb-workspace/mosmodel/mosmodel/mosalloc/src/libmosalloc.so -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 104857600 -bps 180355072 -bs1 0 -be1 0 -bs2 0 -be2 180355072 --analyze --debug ./run.sh

Once you are in the gdb, please make the debugger follow the child processes and move to debug them instead of the parent process by typing in the gdb:
(gdb) set follow-fork-mode child 
Then run the program and send us the backtrace after the segfault happens.

Thanks.

**Comment by CodeATA** [comment] 2021-08-20 06:21
Here is the backtrace log from gdb.
[gdb.log](https://github.com/technion-csl/mosmodel/files/7019520/gdb.log)

Thanks.

**Comment by idanyani** [comment] 2021-08-20 08:03
Thanks for the GDB backtrace!
I can't easily detect the problem and I'm not sure if it's related to Mosalloc or to another code (OpenBLAS, pthread, numpy, ...). Let's try to check which option is correct:
Can you please pull the "master" branch, run "make clean", and then "make" again?
I modified the toy benchmark and removed the call to numpy (see Commit 742cee63). If the new code doesn't face the same problem, we're all good :) If the problem persists, it would be safe to assume that the issue is related to Mosalloc.

**Comment by CodeATA** [comment] 2021-08-20 09:35
Removing the call to numpy indeed solved the segfault problem. However, it seems that I could not generate the pebs hot region file and got the following error messages. I checked mem_bins_4kb.csv in analysis/pebs_tlb_miss_trace. The PAGE_TYPE values are all "unknown". I uploaded the output files in experiments/pebs_tlb_miss_trace/repeat0. Is it an issue caused by my perf?

Thanks.

[experiments.zip](https://github.com/technion-csl/mosmodel/files/7020575/experiments.zip)
[mem_bins_4kb.csv](https://github.com/technion-csl/mosmodel/files/7020581/mem_bins_4kb.csv)

```
perf mem -D --field-separator=';' -i experiments/pebs_tlb_miss_trace/repeat0/perf.data report | \
	sed '1s/,/;/g' | \
	analysis/pebs_tlb_miss_trace/binAddresses.py --width=4096 --output=analysis/pebs_tlb_miss_trace/mem_bins_4kb.csv \
	--pools_range_file=experiments/pebs_tlb_miss_trace/repeat0/pools_base_pointers.out
mem_footprint=106127360
analysis/pebs_tlb_miss_trace/findWeightedWindow.py --input_file=analysis/pebs_tlb_miss_trace/mem_bins_4kb.csv --output_file=analysis/pebs_tlb_miss_trace/hot_region_4kb.txt --memory_footprint=$mem_footprint --page_size=4KB
Input file does not contain page accesses information about the specified pool!
analysis/pebs_tlb_miss_trace/module.mk:38: recipe for target 'analysis/pebs_tlb_miss_trace/hot_region_4kb.txt' failed
make: *** [analysis/pebs_tlb_miss_trace/hot_region_4kb.txt] Error 1
```

**Comment by magbarya** [comment] 2021-08-21 02:21
What CPU model/generation does your test platform have?
I'm asking that because I want to make sure that it fully supports precise event-based sampling (PEBS).

**Comment by CodeATA** [comment] 2021-08-21 04:48
I tested on an Intel Xeon E5-2609 and an Intel Xeon E5-2650. They both encountered this problem.

**Comment by magbarya** [comment] 2021-08-21 20:34
Both of them are SandyBridge, which does not fully support PEBS.
Do you have another machine with a newer CPU generation (i.e., Haswell or newer)?

**Comment by CodeATA** [comment] 2021-08-22 15:27
No, I don't have other machines. If I want to skip the sliding window part, then what I should do is removing the corresponding module in the makefile of "experiments" module, right?
Anyway, we can close this issue. Many thanks for your help.

**Comment by akshaybaviskar** [comment] 2021-08-23 09:26
Hi Mohammad, 

@magbarya
I am also getting the same error as @CodeATA, and I am using Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz which is a SkyLake processor.


```
perf mem -D --field-separator=';' -i experiments/pebs_tlb_miss_trace/repeat0/perf.data report | \
	sed '1s/,/;/g' | \
	analysis/pebs_tlb_miss_trace/binAddresses.py --width=4096 --output=analysis/pebs_tlb_miss_trace/mem_bins_4kb.csv \
	--pools_range_file=experiments/pebs_tlb_miss_trace/repeat0/pools_base_pointers.out
mem_footprint=106295296
analysis/pebs_tlb_miss_trace/findWeightedWindow.py --input_file=analysis/pebs_tlb_miss_trace/mem_bins_4kb.csv --output_file=analysis/pebs_tlb_miss_trace/hot_region_4kb.txt --memory_footprint=$mem_footprint --page_size=4KB
Input file does not contain page accesses information about the specified pool!
make: *** [analysis/pebs_tlb_miss_trace/module.mk:38: analysis/pebs_tlb_miss_trace/hot_region_4kb.txt] Error 1

```

I have attached the complete log after running make  [make_log.txt](https://github.com/technion-csl/mosmodel/files/7030648/make_log.txt)
[mem_bins_4kb.csv](https://github.com/technion-csl/mosmodel/files/7030673/mem_bins_4kb.csv)
[experiments.tar.gz](https://github.com/technion-csl/mosmodel/files/7030734/experiments.tar.gz)

Please let me know if you need anything else.

Thanks,
Akshay

**Comment by CodeATA** [comment] 2021-08-23 12:25
So, how to verify if a CPU supports PEBS? I executed `dmesg | grep PEBS` and got the following output.
```
Performance Events: PEBS fmt2+, Broadwell events, 16-deep LBR, full-width counters, Intel PMU driver.
```
Does it mean that the PEBS is enabled?

**Comment by idanyani** [comment] 2021-08-23 13:27
@CodeATA:

(1) Unfortunately, our current code cannot skip the sliding window experiments because Mosmodel must be built from 54 data points. But you can probably edit the code to remove this dependency.

(2) Based on your dmesg output, it seems like your CPU does support PEBS and that PEBS is enabled. (We once had a SandyBridge processor that contained PEBS errata, as described here: https://access.redhat.com/solutions/634443 . We thought that this errata applies to SandyBridge processors in general, but it might not be the case.)

(3) So the issue you mentioned ("Input file does not contain page accesses information about the specified pool!") is probably not related to PEBS. The fact that @akshaybaviskar faces the same issue is another evidence. We are looking into this :)

**Comment by idanyani** [comment] 2021-08-25 13:33
OK, we believe that we fixed this issue. It was probably a problem with the toy_benchmark: it didn't produce enough TLB misses so the PEBS trace was empty. We re-implemented the toy_benchmark using C++ based on the HPCC benchmark suite.
Please pull the "master" branch, run "make clean", and then "make" again. The entire procedure takes 1--2 hours. Here's an example figure (analysis/all_data/table_walks.pdf) from my machine:
![image](https://user-images.githubusercontent.com/3956430/130799978-96e04d6a-2563-4315-9153-4483c722ab56.png)

**Comment by idanyani** [comment] 2021-08-25 13:34
I'm closing this issue; Please don't hesitate to open another issue if you encounter new problems.

**Closed as completed by idanyani** 2021-08-25 13:34 UTC
